dist: xenial

language: c

compiler:
    - gcc

addons:
    apt:
      packages: [ fakeroot, p7zip-full, autoconf, automake, bison, build-essential,
        flex, gawk, gettext, gperf, libtool, pkg-config, zlib1g-dev, libgmp3-dev,
        libmpc-dev, libmpfr-dev, texinfo, python-docutils, libncurses5-dev, curl,
        autopoint, libltdl-dev, cmake ]

before_script:
    - cp -f ./trunk/tools/travis/* /opt && ./trunk/tools/travis_ci_build_trig.sh
    - mkdir -p /opt/rt-n56u/ && mkdir -p /opt/images/
    - rm -rf toolchain-mipsel/
    - mv -f * .[^.]* /opt/rt-n56u
    - cd /opt/rt-n56u && git clone --depth=1 https://github.com/hanwckf/padavan-toolchain.git toolchain-mipsel
    - chmod u+x ./toolchain-mipsel/toolchain-3.4.x/bin/*
    - ls -Alh /opt/rt-n56u && cd /opt/rt-n56u/trunk/

script:
    - for m in $targets; do fakeroot ./build_firmware_nohup $m && cp -f images/*.trx /opt/images/$m.trx; ./clear_tree_simple >/dev/null 2>&1; done

after_script:
    - GIT_VERSION=`git rev-parse --short=7 HEAD 2>/dev/null` && [ -n "$GIT_VERSION" ] && image_name=images_mt7620_$GIT_VERSION || image_name=images_mt7620
    - cd /opt/images && md5sum *.trx |tee md5sum.txt && 7z a -mx=9 ${image_name}.7z ./*
    - echo $(curl -# --upload-file ./${image_name}.7z https://transfer.sh/${image_name}.7z)

env:
    global:
      - targets="PSG1218 NEWIFI-MINI MI-MINI MI-3 5K-W20 OYE-001"
      - secure: URLT7NCfQa0gh0Uty8uZqvvD9D8RolF0eKwXLIsCy+3w4pd4Qiwe6N/zRew41UZ+cC7PXjZeysc0XjuY58DncW9zEWgFAcfcrikkBaZEZhk6iAu4Y8AgYS5qMynLR6h8SE/QhThJBjIUQGhBNdP9Cze6smqlK0Q1gHbFndfndxcAuf7HaaJPvpV4enV5yyouyC4JBXLkth4yAyidZjHclZeSLzSQQxvU68X2fFLazNRcmqZb2GW8DUx/lCVllScgIFaPXkWlzZEgeESE3kDLoum1zTkf/btJswX+d/mxMOrJiYx/ur+NXhBGyE7yaPCoc+4cpg+R7mPKIGVyJ6WPgQm7lrcn2QWTtYmEizZ0qiCK7yU1hPbOe6VU9QfrbUNVoalYI4Hx0stmiZV1Vpx73L5oy/ZQEAayS7rhSBntN6KozgRPrA/ZqrE6mI1Ky6lQAYfsekqivZq7nNfyV7VSX4A3iZ73NY4LEXrbuordSWIpW9RuIt0i6zfBUD4nDN6PlYnrL7lp4Nq/14TI/x2eq95TQ/+zYk0pT4svp2OKUyOp89k2Y2R25BHCyOVynkwNSk6zN9IgmTyD5TQTV2ceIj61mGbnKkn2+8wWfaSq2IdKmttBfxkVpWlSA7qfCign4WuigClt5Ng7935zIT9UqzIftoESPWaseNy1prbItjk=

git:
    depth: 3
